### ISSUE TITLE
Japanese writing not working well

### ISSUE THREAD

**Issue by hideto0118** [papyrs/papyrs#15] opened 2022-05-27 00:52 UTC
### Bug Behavior

Japanese text written on the title or body goes to next line and is duplicated because the enter key is pushed twice when Japanese is typed.

### Reproduction

Steps to reproduce:

1. Write in Japanese
2. You can see duplicated text at the next line.

### Video about the bug
[Gif](https://i.ibb.co/RhSMHBz/May-26-2022-17-47-51.gif)
### Environment
- Browser(s): Google Chrome
- Operating System: macOS

**Comment by peterpeterparker** [comment] 2022-05-27 05:17
thanks for the issue, duplicate of the StyloJS https://github.com/papyrs/stylo/issues/83

I have trouble replicate it as I don't speak Japanese. If you can help debug it, let me know

**Closed by peterpeterparker** 2022-05-27 05:17 UTC
